[package]
name = "abraca"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.18"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
chrono = { version = "0.4.43", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["chrono", "env-filter"] }
tracing-appender = "0.2"
tokio = { version = "1.46.0", features = ["full"] }
futures = "0.3.31"
async-trait = "0.1.89"
dashmap = "6.1.0"
tokio-tungstenite = { version = "0.28.0", features = ["rustls", "rustls-tls-native-roots"] }
reqwest = { version = "0.13.1", features = ["rustls", "json"] }
